name = "SSExactMajority"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SSExactMajority"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "SSExactMajority"
